spring:
  application:
    name: springboot
  datasource:
    url: jdbc:mysql://localhost:3306/wm?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: null
    password: null
    driver-class-name: com.mysql.cj.jdbc.Driver